---
name: Docker Build & Run
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

# This workflow is only relevant for the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.run_id}}
  cancel-in-progress: true

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@ec657bfcf65d2d4a72a6e61141b85046f069dc06
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile') }}

      - name: Build Image
        shell: bash
        run: docker build -t spond-data-engineer .

      - name: Run Image
        shell: bash
        run: docker run spond-data-engineer
